# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-02 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_auto_20160323_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='PubtatorRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fulfilled', models.BooleanField(default=False)),
                ('session_id', models.CharField(max_length=19)),
                ('request_count', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pubtator',
            name='created',
        ),
        migrations.RemoveField(
            model_name='pubtator',
            name='request_count',
        ),
        migrations.RemoveField(
            model_name='pubtator',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='pubtator',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='pubtator',
            name='validate_cache',
        ),
        migrations.AddField(
            model_name='pubtatorrequest',
            name='pubtator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.Pubtator'),
        ),
    ]
