# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-15 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_auto_20161102_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pubtatorrequest',
            name='fulfilled',
        ),
        migrations.AddField(
            model_name='pubtatorrequest',
            name='status',
            field=models.IntegerField(choices=[(0, b'Unfullfilled'), (1, b'Fullfilled'), (2, b'Failed')], default=0),
        ),
    ]
