# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-30 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_auto_20161114_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubtatorrequest',
            name='status',
            field=models.IntegerField(choices=[(0, b'Unfullfilled'), (1, b'Fullfilled'), (2, b'Failed'), (3, b'Expired')], default=0),
        ),
    ]
