# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-07 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0007_auto_20161130_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubtator',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pubtators', to='document.Document'),
        ),
        migrations.AlterField(
            model_name='pubtator',
            name='kind',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pubtatorrequest',
            name='pubtator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='document.Pubtator'),
        ),
    ]
