# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-20 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_auto_20161207_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='kind',
            field=models.CharField(choices=[('ner', 'Named Entity Recognition'), ('re', 'Relation Extraction')], default='ner', max_length=3),
        ),
        migrations.AlterField(
            model_name='pubtatorrequest',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unfullfilled'), (1, 'Fullfilled'), (2, 'Failed'), (3, 'Expired')], default=0),
        ),
        migrations.AlterField(
            model_name='section',
            name='kind',
            field=models.CharField(choices=[('o', 'Overview'), ('t', 'Title'), ('a', 'Abstract'), ('p', 'Paragraph'), ('f', 'Figure')], max_length=1),
        ),
        migrations.AlterField(
            model_name='section',
            name='source',
            field=models.ImageField(blank=True, default='images/figure.jpg', upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='view',
            name='task_type',
            field=models.CharField(blank=True, choices=[('ner', 'Named Entity Recognition'), ('re', 'Relationship Extraction')], default='ner', max_length=3),
        ),
    ]
