# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-21 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20151130_0410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportmessage',
            name='user',
        ),
        migrations.DeleteModel(
            name='SupportMessage',
        ),
    ]
