# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-20 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity_recognition', '0003_remove_entityrecognitionannotation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityrecognitionannotation',
            name='type_idx',
            field=models.IntegerField(blank=True, choices=[(0, 'Disease'), (1, 'Gene'), (2, 'Treatment')], null=True),
        ),
    ]
