# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-28 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='rating_score',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='rating_votes',
        ),
    ]
