# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-20 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import mark2cure.userprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20160928_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='images/default.jpg', upload_to=mark2cure.userprofile.models._content_file_name),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='education',
            field=models.IntegerField(blank=True, choices=[(0, 'Some elementary'), (1, 'Finished elementary'), (2, 'Some high school'), (3, 'Finished high school'), (4, 'Some community college'), (5, 'Finished community college'), (6, 'Some 4-year college'), (7, 'Finished 4-year college'), (8, 'Some masters program'), (9, 'Finished masters program'), (10, 'Some PhD program'), (11, 'Finished PhD program')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='science_education',
            field=models.IntegerField(blank=True, choices=[(0, 'Some elementary'), (1, 'Finished elementary'), (2, 'Some high school'), (3, 'Finished high school'), (4, 'Some community college'), (5, 'Finished community college'), (6, 'Some 4-year college'), (7, 'Finished 4-year college'), (8, 'Some masters program'), (9, 'Finished masters program'), (10, 'Some PhD program'), (11, 'Finished PhD program')], default=None, null=True),
        ),
    ]
