# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20170919_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(blank=True, help_text='You can create a new team.', max_length=100, verbose_name='Team Name'),
        ),
    ]
