"""NCBO User relationship fix datetime

Revision ID: 1749147f5093
Revises: dea060d500c
Create Date: 2013-11-08 10:45:54.585107

"""

# revision identifiers, used by Alembic.
revision = '1749147f5093'
down_revision = 'dea060d500c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
