"""adding mturk int field on annotations table

Revision ID: 2c955a092e7d
Revises: 38c954341d1a
Create Date: 2013-11-06 13:44:00.129020

"""

# revision identifiers, used by Alembic.
revision = '2c955a092e7d'
down_revision = '38c954341d1a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation', sa.Column('experiment', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annotation', 'experiment')
    ### end Alembic commands ###
