"""init

Revision ID: 38c954341d1a
Revises: 5ae64b3fd058
Create Date: 2013-10-15 14:20:12.734728

"""

# revision identifiers, used by Alembic.
revision = '38c954341d1a'
down_revision = '5ae64b3fd058'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
