"""Init of AMT specific requirements

Revision ID: 40315d52ade8
Revises: None
Create Date: 2013-10-04 20:47:53.626532

"""

# revision identifiers, used by Alembic.
revision = '40315d52ade8'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('kind', sa.String(length=12), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'kind')
    ### end Alembic commands ###
