"""Integration of Flask-Login

Revision ID: 8634863f8e1
Revises: 40315d52ade8
Create Date: 2013-10-06 19:38:23.352907

"""

# revision identifiers, used by Alembic.
revision = '8634863f8e1'
down_revision = '40315d52ade8'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('admin', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('mturk', sa.Boolean(), nullable=True))
    op.drop_column('user', u'kind')
    op.drop_column('user', u'api_key')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column(u'api_key', mysql.TEXT(), nullable=True))
    op.add_column('user', sa.Column(u'kind', mysql.VARCHAR(length=12), nullable=True))
    op.drop_column('user', 'mturk')
    op.drop_column('user', 'admin')
    op.drop_column('user', 'active')
    ### end Alembic commands ###
