"""NCBO User relationship

Revision ID: dea060d500c
Revises: 2c955a092e7d
Create Date: 2013-11-08 09:49:01.576322

"""

# revision identifiers, used by Alembic.
revision = 'dea060d500c'
down_revision = '2c955a092e7d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ncbo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('min_term_size', sa.DateTime(), nullable=True),
    sa.Column('score', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ncbo')
    ### end Alembic commands ###
