# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-28 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20160523_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentquestrelationship',
            name='points',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='points',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='provides_qualification',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='requires_qualification',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userquestrelationship',
            name='score',
            field=models.IntegerField(blank=True, default=5),
        ),
    ]
