# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-20 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20160928_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='task_type',
            field=models.CharField(choices=[('ner', 'Name Entity Recognition'), ('re', 'Relation Extraction')], max_length=3),
        ),
        migrations.AlterField(
            model_name='task',
            name='kind',
            field=models.CharField(choices=[('t', 'Training'), ('q', 'Quest')], default='q', max_length=1),
        ),
        migrations.AlterField(
            model_name='userquestrelationship',
            name='views',
            field=models.ManyToManyField(help_text='The 10 (5 Quests * 2 Sections) Viewable blocks of text that are part of the Quest', to='document.View'),
        ),
    ]
