# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20170919_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=8)),
                ('task_type', models.CharField(choices=[('ner', 'Name Entity Recognition'), ('re', 'Relation Extraction')], max_length=3)),
                ('name', models.CharField(max_length=200)),
                ('order', models.IntegerField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='level',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completes', to='task.Requirement'),
        ),
    ]
