# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-08 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_remove_task_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='task',
            name='meta_url',
        ),
        migrations.RemoveField(
            model_name='task',
            name='provides_qualification',
        ),
        migrations.RemoveField(
            model_name='task',
            name='requires_qualification',
        ),
    ]
