# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_auto_20180108_0403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'get_latest_by': 'created', 'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='requirement',
            options={'get_latest_by': 'order', 'ordering': ('-order',)},
        ),
        migrations.RemoveField(
            model_name='level',
            name='level',
        ),
        migrations.RemoveField(
            model_name='level',
            name='task_type',
        ),
    ]
