# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-28 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import mark2cure.download.models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=mark2cure.download.models._download_file_name),
        ),
    ]
