# A Gemfile describes the gem dependencies 
# required to execute associated Ruby code.
#
# http://bundler.io/v1.5/man/bundle.1.html

# Rubygems Source
source "https://rubygems.org"

# Ruby Version
ruby '2.2.2'

# Gem Dependencies - Compass & Sass
# Required Deps for Breakpoint Gem
gem 'compass', '~> 1.0.3'
gem 'susy', '~> 2.2.2'
gem "breakpoint", '~> 2.5.0'